# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PREPROD_HOST }}
        username: ${{ secrets.PREPROD_USER }}
        password: ${{ secrets.PREPROD_PASSWORD }}
        port: ${{ secrets.PREPROD_PORT }}
        script: |
          cd ~/tg-dev-gitaction
          git pull origin main
          npm install 
          pm2 restart tg-dev-backend
